### ISSUE TITLE
Fill the database

### ISSUE THREAD

**Issue by ElenaNyiazova** [ElenaNyiazova/FarmFood#11]
Fill the database with test data such as: sellers, buyers, products, product groups.

**Comment by vito-a** [comment]
The database is filled with the default initial test data - users, products, categories etc. (please also see the screenshots attached).

![Screenshot 2021-12-14 112754](https://user-images.githubusercontent.com/9512653/145971827-aa7f62bb-5ae8-4e5f-a7e6-e65bf73b86dc.png)

![Screenshot 2021-12-14 112831](https://user-images.githubusercontent.com/9512653/145971863-268ebc1d-101d-46a6-a2d2-f7566cf554fc.png)

![Screenshot 2021-12-14 112901](https://user-images.githubusercontent.com/9512653/145971874-0e9c73cc-0d47-4c1c-8700-2c47b164b3bc.png)

All the database structure and data are exported, committed to the https://github.com/ElenaNyiazova/FarmFood/blob/master/sql/farmfood.sql and deployed to Heroku.
