### ISSUE TITLE
access to the database

### ISSUE THREAD

**Issue by ElenaNyiazova** [ElenaNyiazova/FarmFood#23]
access to the database, the task is to check that our proposals are correctly connected to the database if something is wrong to establish the work

**Comment by vito-a** [comment]
As you know, besides being deployed to Heroku, all the database structure and data are exported and committed to the https://github.com/ElenaNyiazova/FarmFood/blob/master/sql/farmfood.sql . Everything is there, we can set it up locally and demo from the local machine if needed.

Please use it on your local PostgreSQL server to test the connection.

**Comment by vito-a** [comment]
Heroku database connection established

![Screenshot 2021-12-15 131131](https://user-images.githubusercontent.com/9512653/146177472-41dcafe2-ed37-4107-a6c8-000754f86e59.png)
d
